name: Dependency check builder
on:
  schedule:
    - cron:  '0 0 * * *'
  workflow_dispatch:

env:
  EMAIL_ADDRESS: "scholz@minova.aero"
  REGISTRY: ghcr.io

jobs:
  depcheck-builder:
    runs-on: ubuntu-latest
    name: Dependency_check_builder
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Declare some variables
        id: vars
        shell: bash
        run: |
          echo "::set-output name=github_sha_short::$(git rev-parse --short HEAD)"

      - name: Get Time
        id: time
        uses: nanzm/get-time-action@v1.1
        with:
          timeZone: 0
          format: 'YYYYMMDD'

      - name: Build & push Docker image
        uses: mr-smithers-excellent/docker-build-push@v5
        with:
          image: 'dependency-check-action'
          addLatest: true
          tags: ${{ steps.time.outputs.time }}_${{ steps.vars.outputs.github_sha_short }}
          dockerfile: ./Dockerfile
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_PASSWORD }}
