name: Dependency check builder
on:
  schedule:
    - cron:  '0 2 * * *'
  workflow_dispatch:

env:
  EMAIL_ADDRESS: "scholz@minova.aero"
  REGISTRY: ghcr.io

jobs:
  depcheck-builder:
    runs-on: ubuntu-latest
    name: Dependency_check_builder
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: get date
        id: time
        uses: boredland/get-time-action@2.0.0
        with:
          timeZone: UTC
          format: 'YYYYMMDD'

      - name: prepare container image name
        id: container-name-and-githash
        shell: bash
        run: |
          GITHUB_SHA_SHORT=$(git rev-parse --short HEAD)
          echo "github_sha_short=$GITHUB_SHA_SHORT" >> $GITHUB_OUTPUT
          echo "container-image=${{inputs.registry}}/${{github.repository_owner}}/${{github.event.repository.name}}:${{ steps.time.outputs.time }}_$GITHUB_SHA_SHORT" >> $GITHUB_OUTPUT

      - name: build & push container image '${{ steps.container-name-and-githash.outputs.container-image }}'
        uses: mr-smithers-excellent/docker-build-push@v6
        with:
          image: 'dependency-check-action'
          addLatest: true
          tags: ${{ steps.time.outputs.time }}_${{ steps.container-name-and-githash.outputs.github_sha_short }}, latest
          dockerfile: ./Dockerfile
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_PASSWORD }}